### ISSUE TITLE
Move assets unchanged between versions to assets/core/ directory

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#1002]
The version-specific asset directories should be overrides, not full dumps.
Presumably, lots of files won't have changed between versions.

There's a number of sub-tasks here:

1. Figure out which assets are different between versions (for now, we could just compare us and pal?) - need a script for this
2. Somehow tell splat the output folder for each asset, or move assets post-split
3. Add `core` to the asset stack of all versions

**Comment by ethteck** [comment]
Duplicate of #392
