### ISSUE TITLE
New properties at the end of a struct don't get shifted properly

### ISSUE THREAD

**Issue by Pronyo-Chan** [pmret/papermario#1034]
Adding more data in existing structs seem to work fine with shiftability when it's in the middle, but when adding it at the end, it causes some weird issues. I made a simple example to illustrate the problem:
https://github.com/Pronyo-Chan/soloventure/commit/967202b57bd5fb6d52a0ec6ec062f3c29b33425f

1) Add 3 newVars at the end of the PlayerStatus struct
2) In reset_player_status(), assign some values to these newVars
3) To easily debug their values, edit the pause screen to display the newVar values instead of coins, star pieces and starpoints

If you test on my commit on any map, you'll see that newVar1 doesn't have the assigned value. You'll even see it fluctuate if you move around the map enough...It seems to share a memory address with something else.

Now, just move these newVars higher in the struct, like in the following commit: https://github.com/Pronyo-Chan/soloventure/commit/ce642d3e9fe73d1653b18e62202e28562bd30a6b and recompile.

Test again and sure enough! The assigned values are displayed properly on the pause screen.

**Comment by Rainchus** [comment]
This should be fixed as of the bss shifting PR

**Comment by ethteck** [comment]
Closin
