### ISSUE TITLE
EnableIdleScript needs an enum

### ISSUE THREAD

**Issue by Ponmander** [pmret/papermario#1041]
EnableIdleScript has three 3 cases so it's exactly a bool. -1 restarts the Idle Script. 0 disables it. 1 enables it. So -1 could have an enum called RESTART.

**Comment by nanaian** [comment]
I'm thinking:
```c
enum IdleScriptState {
    IDLE_SCRIPT_ENABLE,
    IDLE_SCRIPT_DISABLE,
    IDLE_SCRIPT_RESTART = -1,
};
```

**Comment by nanaian** [comment]
`EnableIdleScript` would also need to change name to, for example, `SetIdleScriptState`. Not sure what the best name is

**Comment by Ponmander** [comment]
> `EnableIdleScript` would also need to change name to, for example, `SetIdleScriptState`. Not sure what the best name is

Oh yeah true. There's like two things relating to Idle when it comes to handleEvent, nextTurn, and takeTurn scripts or anything that gets executed inside said scripts.

**Comment by HailSanta** [comment]
Ah yeah, this is noted in the Star Rod docs. I was kinda holding off on this since there are a couple functions that work this way and I wanted to ensure the enum values are consistent among them. The others are EnablePlayerBlur and EnableActorBlur.

**Comment by Ponmander** [comment]
Yeah I am guessing we would put the RESET enum in enums.h I think?

**Comment by nanaian** [comment]
Better script_api.h I think
