### ISSUE TITLE
install.sh doesn't understand what distro Manjaro arm64 is

### ISSUE THREAD

**Issue by coreybruce** [pmret/papermario#1050]
Hey I just wanted to report that the install script doesn't seem to know what Manjaro arm64 is which is based on Arch.

```
The following distros (and their derivatives) are supported by install.sh:
- Debian/Ubuntu (apt)
- Arch Linux (pacman)
- openSUSE (zypper)
- Alpine Linux (apk)
Please consider contributing and adding an installation script for your distro.
```

**Comment by nanaian** [comment]
This line is the condition: https://github.com/pmret/papermario/blob/5511e18133694cf78979e29df65d931371350aab/install.sh#L63

What does your `/etc/os-release` say on Manjaro?

**Comment by coreybruce** [comment]
> This line is the condition:
> 
> https://github.com/pmret/papermario/blob/5511e18133694cf78979e29df65d931371350aab/install.sh#L63
> 
> What does your `/etc/os-release` say on Manjaro?

```
NAME="Manjaro ARM"
ID="manjaro-arm"
ID_LIKE="manjaro arch"
PRETTY_NAME="Manjaro ARM"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/c/arm/"
LOGO=manjarolinux
```

**Comment by ethteck** [comment]
Closing in favor of #1059
