### ISSUE TITLE
Message building should respect the asset stack

### ISSUE THREAD

**Issue by Wrymouth** [pmret/papermario#1089]
There's a message I want to change in the file `us/msg/1E_Choices.msg` so I create a file `test/msg/1E_Choices.msg`. Then I copy the message I want to replace into that file and make the changes. Ninja fails to build because of undeclared message ids (because it didn't look at the original file, only the custom file).

**Comment by nanaian** [comment]
This is intended behaviour as discussed in Discord. You can create a new msg file and overwrite the message from there, just declare that it is to be used by adding to the files list in the `pm_msg` segment in `splat.yaml`.
