### ISSUE TITLE
Cannot properly build the decomp

### ISSUE THREAD

**Issue by SomeRandoPeep** [pmret/papermario#1191]
I'm new to this, I followed the instructions on how to build the game from the common section (using Ubuntu), but whenever I get to the ./configure step the terminal says "ModuleNotFoundError: No module named 'ninja_syntax". I don't know what I'm doing wrong, would be nice if someone could help :(

**Comment by ethteck** [comment]
Hey - you'll want to install all the packages in our requirements.txt. In this case, it appears `ninja_syntax` is missing. You can install the packages there with `pip install -U -r requirements.txt`

**Comment by SomeRandoPeep** [comment]
Thank you, and sorry again-

**Comment by ethteck** [comment]
no need to apologize! happy to help :)
