### ISSUE TITLE
TTYD Decompilation

### ISSUE THREAD

**Issue by JPC16** [pmret/papermario#1221]
Seeing that you have finished with the decompilation of several versions of Paper Mario 64, with the Japanese version still to be finished, do you think you would start another decompilation project but this time for its Gamecube sequel The Thousand Year Door?

**Comment by ethteck** [comment]
TTYD has an existing decomp project at https://github.com/NWPlayer123/PaperMario2 , which you're welcome to get involved with if you want to join the paper mario decomp discord (linked on our site & github) :)

**Comment by JPC16** [comment]
I saw that TTYD decompilation project from that link you sent me and it is currently inactive as it has not been updated since 2023.

**Comment by ethteck** [comment]
Yeah, it needs active contributors, which is why I'm saying you can join and get involved if you're interested :)
