### ISSUE TITLE
Modifying the linker script seems to trigger a rebuild for many C files

### ISSUE THREAD

**Issue by Mr-Wiseguy** [pmret/papermario#230]
Fixing this issue will allow much quicker iteration when reorganizing the layout of source files, such as matching libultra functions.

**Comment by nanaian** [comment]
This is for any file that includes `ld_addrs.h`, since that is directly generated from the linker script, and is intended. Potential solution ideas are welcome

**Comment by Mr-Wiseguy** [comment]
Ah, okay. I like to do manual edits to the linker script to bypass having to run configure again as a time saver, which is how I ran into this. If I come up with a solution I'll open another issue or PR it.
