### ISSUE TITLE
Add wine32 to install.sh for Alpine, OpenSUSE

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#231]
See #224

**Comment by nanaian** [comment]
@Gorialis do you know how to install 32-bit WINE on Alpine and OpenSUSE? According to `git blame` you added those distros to `install.sh`

**Comment by nanaian** [comment]
Ubuntu/Debian support added in https://github.com/pmret/papermario/commit/c8d11afc542763059e4533d27cc4ce6d8cd5e08f

**Comment by ethteck** [comment]
Closing but will re-open when we get to #239
