### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#366]
Compiling the rom emits a ton of warnings that we should be able to fix - mostly implicit casts that should really be made explicit.
Additionally it would be nice to be able to enable `-Wimplicit -Wredundant-decls` so headers are used properly.

Once this is done we can enable `-Werror` on Jenkins so people fix their warnings as they match stuff :shipit:

**Comment by imkhali** [comment]
Hi nanaian,
I think I can do this

**Comment by ethteck** [comment]
Let us know if you have any questions! Feel free to reach out on discord as well. @imkhali

**Comment by nanaian** [comment]
We should remove `-Wshadow` entirely because the DL-building macros emit `warning: declaration of `_g' shadows previous local`

**Comment by ethteck** [comment]
I think this can be closed now. We've severely reduced the number of warnings and continue to do so

**Comment by ethteck** [comment]
Gonna close, but someone can re-open if they disagree. I mostly think this is moot cause it was made before the warning check system / Bowser Slug entered the fray
