### ISSUE TITLE
Parameterise all flags as enums

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#391]
We currently parameterise only some flags, like NPC flags, in `enums.h`. Ideally, we'd do this for _all_ flag types, such as that of BattleStatus.

**Comment by Brotenko** [comment]
A list of yet to be parameterised flags:

- [ ] ColliderFlags
- [ ] ColliderBoundingBoxFlags
- [ ] PlayerStatusFlags
- [ ] PlayerStatusAnimFlags
- [ ] BattleStatusFlags1
- [ ] BattleStatusFlags2
- [ ] BattleStatusRushesFlags
- [ ] BattleStatusCurrentTargetListFlags
- [ ] BattleStatusTattleFlags
- [ ] CameraInitDataFlags
- [ ] CameraFlags
- [ ] CameraMoveFlags 
- [ ] CameraPrevFollowFlags
- [ ] CameraPrevPrevFollowFlags
- [ ] StaticItemTargetFlags
- [ ] StaticItemTypeFlags
- [ ] NpcFlags
- [ ] MessagePrintStateFlags
- [ ] MessagePrintStateDelayFlags
- [ ] GameStatusPeachFlags
- [ ] GameStatusDemoFlags
- [ ] MessageDrawStatePrintModeFlags
- [ ] MessageDrawStateEffectFlags
- [ ] ActorPartEventFlags
- [ ] ActorPartFlags3
- [ ] EvtGroupFlags (u8)
- [ ] EntityCollisionFlags (u8)
- [ ] ShopInventoryItemFlags
- [ ] EncounterResetMapEncounterFlags
- [ ] EncounterDefeatFlags
- [ ] SaveDataEnemyDefeatFlags
- [ ] SaveDataGlobalFlags
- [ ] SaveDataAreaFlags
- [ ] EnemyDropsFlags

Names have been chosen by me - The respective data structs that hold these flags are easy to find this way.
