### ISSUE TITLE
Migrate map and battle data to C

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#545]
This is the first pass of map/battle data work. Future passes will involve disassembling scripts and other structs, moving any assets into actual files (and not including them in raw form in the repo!), documenting, etc.

This can probably be achieved with a simple script that takes in a `.data.s` or `.rodata.s` file and spits out an equivalent `.c` file, with each piece of data being an s32 array.

**Comment by JoshDuMan** [comment]
As current progress on this, about half of battle is currently done. My process for these files is to use the star_rod_idx_to_c.py tool to generate C for the data, then go about tweaking the output by hand to split it into the correct files and fix data not supported by the tool. The output I create isn't the final step and will need cleaned up later.
