### ISSUE TITLE
only Debian/Ubuntu is supported for building rom

### ISSUE THREAD

**Issue by Alto1772** [pmret/papermario#625]
Only some Linux distros with **cpp-mips-linux-gnu** package is supported right now, because of KMC gcc compiler executing mips-linux-gnu-cpp which it does not available for some distros. You can fix this by asking _Pink Horned Man White Nose_ to use the host's cpp, or if he doesn't want to do it use [mine](https://github.com/Alto1772/kmc-exew32-loader) instead. _(I will tell more about it if you agree to use my version of his.)_

### Build running on Arch Linux:
![2022-01-18_16-49](https://user-images.githubusercontent.com/56553686/149910523-ef02ba32-02ed-4bd5-a267-c95dfbe198bf.png)

**Comment by Alto1772** [comment]
oh yeah i do came out of nowhere if i wanted to

**Comment by ethteck** [comment]
Pink Horned Man White Nose??? lol

**Comment by ethteck** [comment]
<img width="235" alt="image" src="https://user-images.githubusercontent.com/2985314/149921285-c18bef7a-513c-4958-bdc9-37edf69aad36.png">
omfg lollll

**Comment by Alto1772** [comment]
> _[Mr-Wiseguy pfp]_
> omfg lollll

yep thats the guy...

because there's a problem in his **kmc-gcc-wrapper** program:
- It replaces the `int 0x21` to execute **SIGTRAP** for handler.
- It relies heavily on subroutines redirecting to its **"wrappers"**.
- Everything loaded/patched is **hardcoded** on every executable.

So I made my own program ([kmc-exew32-loader](https://github.com/Alto1772/kmc-exew32-loader)) to circumvent those. Feel free to test it out for yourself...

**Comment by ethteck** [comment]
I'm a little more tempted to stick with wiseguy's wrapper because it's kind of more of a "standard" in the community, and he's easier to reach and ask questions about it, being active on discord and stuff. (It's totally fine that you're not on discord, but it just makes collaborating a little harder)

It may make more sense to integrate changes to his repo that you feel would be ideal. Also we can involve him in this discussion @Mr-Wiseguy

**Comment by ethteck** [comment]
Pink Horned Man White Nose (who I shall refer to as PHMWN from here on) informed me we should be able to use an unmodified gcc 2.7.2.1 instead, to build libultra. so I'll be investigating that soon and will update here with more details. We may be able to avoid wrappers for kmc altogether

**Comment by Alto1772** [comment]
> I'm a little more tempted to stick with wiseguy's wrapper because it's kind of more of a "standard" in the community

Aww, that's so sad no one in the community had tested my first C program. :(
But that is ok, I just need to request some changes to replace **mips-linux-gnu-cpp** with just only **cpp** to work on some distros.

> It's totally fine that you're not on discord

Well, I do have one but i use it frequently, plus i dont want to join that modding discord for my embarrassment and spoiled.

> Pink Horned Man White Nose (who I shall refer to as PHMWN from here on) informed me we should be able to use an unmodified gcc 2.7.2.1 instead, to build libultra.

[Here some instructions](https://virtuallyfun.com/wordpress/2016/10/20/n64-cross-gcc-binutils-for-win32/) to compile the same versions that kmc uses, in windows 95 (i don't know if its the right way). it just needs some tweaks to work on linux.

**Source tarballs that he used from the link**: 
https://ftp.gnu.org/gnu/binutils/binutils-2.8.1.tar.gz
https://ftp.gnu.org/old-gnu/gcc/gcc-2.7.2.3.tar.gz
https://ftp.gnu.org/gnu/make/make-3.82.tar.gz

**Comment by JoshDuMan** [comment]
Yeah, the obvious upside of using GCC 2.7.2.1 is that we can actually support building on Mac, which means we won't need to include the assembly code as we do (which seems like a major upside to me).

**Comment by Alto1772** [comment]
but there is a problem with that gcc version, it does not have the vr4300 mul bug fix option, so...

Also, this isn't a discussion for a plan to replace kmc gcc with gcc 2.7.2.1, make another issue for that. (I won't make another one, it's ur choice).

**Comment by ethteck** [comment]
> Well, I do have one but i use it frequently, plus i dont want to join that modding discord for my embarrassment and spoiled.
I don't understand why joining PMM would be embarrassing or what you would get spoiled. We don't share spoilers for anything in the decomp-64 channel. Maybe this is a language barrier thing?

> Also, this isn't a discussion for a plan to replace kmc gcc with gcc 2.7.2.1, make another issue for that.
I appreciate your sporadic contributions to this project, but do not talk to project maintainers like this. This issue is related to what Josh and I are talking about, so it's totally fine to have the discussion here.

**Comment by ethteck** [comment]
We just removed the kmc gcc wrapper from the repo, so this should no longer be a problem. Closing :)
