### ISSUE TITLE
Tracker but you can type

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#824]
As tosh is to scratch, this issue is to the tracker

**Comment by pixel-stuck** [comment]
???

**Comment by ethteck** [comment]
whatcha talkin aboot

**Comment by Brotenko** [comment]
Is tosh with us in the room right now?

**Comment by ethteck** [comment]
I am following the clues left behind, and I came upon https://tosh.blob.codes/ - but what I don't get is why you're calling this a tracker? Do you mean a modding tool?

**Comment by ethteck** [comment]
fish solved the other half of the mystery. you meant this for https://github.com/nanaian/mamar

**Comment by nanaian** [comment]
oops

**Comment by cglmrfreeman** [comment]
What a ride this was
