### ISSUE TITLE
Remove underscores from all npc anim names

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#840]
The conventions comment at the top of `npc.yaml` says

> Names should be short, one or two words, in PascalCase with no underscores.

There are a number of animation names that use underscores (search the file for '_'); we should remove the underscores.
This will mean updating the places where said animations are used.

**Comment by YashPimple** [comment]
@nanaian can you assign it to me would like to work on this issue.

**Comment by Brotenko** [comment]
Go at it @YashPimple! Good luck 👍

**Comment by nanaian** [comment]
@YashPimple feel free to message [on Discord](https://discord.com/invite/urUm3VG) (#decomp-64) if you need any help 😄

**Comment by HailSanta** [comment]
To be clear, this should only apply to "frames" and "animations". Underscores in palette names are deliberate and meaningful.

**Comment by nanaian** [comment]
@HailSanta can you clarify what underscores in palette names signify?

**Comment by HailSanta** [comment]
Usually, they are meant to correspond with variation names. e.g., Koopa Troop has variations DarkTroopa, Default, and FrostTroopa; and palettes Dark_Poisoned, Poisoned, Frost_Poisoned, etc (Default variations have no prefix).
