### ISSUE TITLE
JP pm_msg

### ISSUE THREAD

**Issue by nanaian** [pmret/papermario#940]
![image](https://user-images.githubusercontent.com/9429556/218333404-8b13a6ac-b9d8-4003-9b1e-4f1c0bc0a022.png)
![image](https://user-images.githubusercontent.com/9429556/218333410-639d79ab-7eab-44e2-976f-c565a9265696.png)

**Comment by marijnvdwerf** [comment]
Credits fonts appear to be the same

![pmjp-font3](https://user-images.githubusercontent.com/737603/218334433-aea6a158-fe12-484d-bcda-2ce88f676314.png)
![pmjp-font4](https://user-images.githubusercontent.com/737603/218334436-157dd012-54ed-4404-bb90-c6ed811ecd9f.png)
